sudo: required
services:
  - docker

before_install:
  - docker build -t thomastygreat/react-test -f  ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thomastygreat/react-test npm test -- --coverage

after_success:
  - docker build -t thomastygreat/multi-client ./client
  - docker build -t thomastygreat/multi-nginx ./nginx
  - docker build -t thomastygreat/multi-server ./server
  - docker build -t thomastygreat/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push thomastygreat/multi-client
  - docker push thomastygreat/multi-nginx
  - docker push thomastygreat/multi-server
  - docker push thomastygreat/multi-worker